name: Build Cards

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Build'
        # Default value if no value is explicitly provided
        default: 'Build'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      volumes:
        - /proc:/proc
        - /sys/fs/cgroup/systemd/actions_job:/sys/fs/cgroup/systemd/actions_job
        - /sys/fs/cgroup:/sys/fs/cgroup
      options: --privileged

    steps:
    - name: Clone build scripts
      uses: actions/checkout@v1
      
    - name: Setup Build Environment
      run: |
        chmod +x ./setup.sh
        ./setup.sh
        
    - name: AUR Packages
      run: |
        chmod +x ./aur.sh
        ./aur.sh
        
    - name: Normal Packages
      run: |
        chmod +x ./nor.sh
        ./nor.sh       
        
    - name: Daemons and services
      run: |
        chmod +x ./dae.sh
        ./dae.sh       

    - name: Build & bundle disk image
      run: |
        chmod +x ./build.sh
        ./build.sh
        
    - name: Upload disk image
      uses: actions/upload-artifact@v2.1.4
      with:
        name: cards
        path: ~/cards-*.*.*-x86_64.iso
        if-no-files-found: error

    - name: Upload build profile
      uses: actions/upload-artifact@v2.1.4
      with:
        name: profile
        path: ~/cards-profile
        if-no-files-found: error

    - name: Upload local repository
      uses: actions/upload-artifact@v2.1.4
      with:
        name: local_repo
        path: ~/local-repo
        if-no-files-found: error
