# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt install build-essential make libncurses5-dev libncursesw5-dev perl mkisofs -y > /dev/null
          
          export LINUX_VERSION=5.9-rc6
          export BINUTILS_VERSION=2.35
          export GCC_VERSION=10.2.0
          export GMP_VERSION=6.2.0
          export MPFR_VERSION=4.1.0
          export MPC_VERSION=1.2.0
          export GLIBC_VERSION=2.32
          export BUSYBOX_VERSION=1.32.0
          export CLFS_BOOTSCRIPTS_VERSION=3.0-20140521
          export PACMAN_VERSION=5.2.2
          
          chmod +x ./build-cards.sh
          ./build-cards.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          # Artifact name
          # A file, directory or wildcard pattern that describes what to upload
          path: ~/cards-copy/cards.iso
