name: Build Cards

on:
  push:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Build'
        # Default value if no value is explicitly provided
        default: 'Build'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      volumes:
        - /proc:/proc
        - /sys/fs/cgroup/systemd/actions_job:/sys/fs/cgroup/systemd/actions_job
        - /sys/fs/cgroup:/sys/fs/cgroup
      options: --privileged

    steps:
    - name: Clone build scripts
      uses: actions/checkout@v1
      
#    - name: Run Tests
#      run: |
#        chmod +x ./test.sh
#        ./test.sh

    - name: Build & bundle disk image
      run: |
        chmod +x ./setup.sh
        ./setup.sh
        
    - name: Upload disk image
      uses: actions/upload-artifact@v2.1.4
      with:
        name: cards
        path: ~/cards-*.*.*-x86_64.iso
        if-no-files-found: error
